/// Flutter icons Tiny
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Tiny
///      fonts:
///       - asset: fonts/Tiny.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Tiny {
  Tiny._();

  static const _kFontFam = 'Tiny';
  static const String _kFontPkg = null;

  static const IconData clap =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disagree =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrong =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
